# Generated by Django 5.0.2 on 2025-05-26 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ads", "0002_alter_anzeige_options_remove_anzeige_bilder_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Nachrichtentext")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zeitstempel"),
                ),
                ("gelesen", models.BooleanField(default=False, verbose_name="Gelesen")),
                (
                    "anzeige",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ads.anzeige",
                        verbose_name="Anzeige",
                    ),
                ),
                (
                    "empfaenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Empfänger",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Absender",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nachricht",
                "verbose_name_plural": "Nachrichten",
                "ordering": ["-timestamp"],
            },
        ),
    ]
