# Generated by Django 5.0.2 on 2025-05-30 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0002_alter_anzeige_options_remove_anzeige_bilder_and_more"),
        (
            "messaging",
            "0002_alter_message_options_rename_gelesen_message_is_read_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="ads.anzeige",
                verbose_name="Anzeige",
            ),
        ),
    ]
