# Generated by Django 5.0.2 on 2025-06-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0003_conversation_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="message_files/"),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nachrichtentext"
            ),
        ),
    ]
