# Generated by Django 5.0.2 on 2025-05-23 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anzeige",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                ("beschreibung", models.TextField()),
                (
                    "bilder",
                    models.ImageField(
                        blank=True, null=True, upload_to="anzeigen_bilder/"
                    ),
                ),
                ("preis", models.DecimalField(decimal_places=2, max_digits=10)),
                ("erstellungsdatum", models.DateTimeField(auto_now_add=True)),
                ("kategorie", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktiv", "Aktiv"),
                            ("verkauft", "Verkauft"),
                            ("deaktiviert", "Deaktiviert"),
                        ],
                        default="aktiv",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anzeigen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
