# Generated by Django 5.2 on 2025-05-23 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anzeige",
            options={"verbose_name": "Anzeige", "verbose_name_plural": "Anzeigen"},
        ),
        migrations.RemoveField(
            model_name="anzeige",
            name="bilder",
        ),
        migrations.CreateModel(
            name="AnzeigeBild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bild", models.ImageField(upload_to="anzeigen_bilder/")),
                (
                    "anzeige",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bilder",
                        to="ads.anzeige",
                    ),
                ),
            ],
        ),
    ]
