# Generated by Django 5.0.2 on 2025-07-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
